library(geneplast)
library(AnnotationHub)
library(vroom)
library(dplyr)

set.seed(1024)

get_string_ids <- function(ids, species = "9606") {
  ids_collapsed <- paste0(ids, collapse = "%0d")

  jsonlite::fromJSON(
    RCurl::postForm(
      "https://string-db.org/api/json/get_string_ids",
      identifiers = ids_collapsed,
      echo_query  = "1",
      species = species
    ),
  )
}

gene <- c("FGFR3", "ALDH1L1", "S100B")

string_id <- get_string_ids(gene) %>%
  janitor::clean_names() %>%
  dplyr::select(-c(query_index)) %>%
  tidyr::separate(string_id, into = c("ssp_id", "string_id"), sep="\\.")

## Get geneplast databases

ah <- AnnotationHub()

meta <- query(ah, "geneplast")

load(meta[["AH83116"]])

# Takes a lot of RAM to do:
# Cog Mappings (cogdata.tsv) generated by bin/create_cog_map.sh
cogs_of_interest <- cogdata %>%
  filter(ssp_id %in% string_id$ssp_id) %>%
  filter(protein_id %in% string_id$string_id) %>%
  select(-ssp_id) %>%
  left_join(string_id, by = c("protein_id" = "string_id"))

gc()

ogr <- groot.preprocess(cogdata=cogdata, phyloTree=phyloTree,cogids = cogs_of_interest$cog, spid="9606")

ogr <- groot(ogr, nPermutations=1000, verbose=FALSE)

res <- groot.get(ogr, what="results")

## Naming the rooted clades and getting the final results table
CLADE_NAMES <- "https://raw.githubusercontent.com/dalmolingroup/neurotransmissionevolution/ctenophora_before_porifera/analysis/geneplast_clade_names.tsv"

lca_names <- vroom(CLADE_NAMES)

groot_df <- res %>%
  tibble::rownames_to_column("cog_id") %>%
  select(cog_id, root = Root) %>%
  left_join(lca_names) %>%
  left_join(cogs_of_interest)

View(groot_df)
